version: "3.3"
services:
  postgres:
    image: postgres:13.7-alpine
    env_file:
      - .dev.db.env
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go_user -d go_rest"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G